# Generated by Django 4.2.7 on 2024-06-15 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockuser', '0002_stocks_sector'),
    ]

    operations = [
        migrations.CreateModel(
            name='fundamental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eps', models.FloatField()),
                ('market_cap', models.BigIntegerField()),
                ('roe', models.FloatField()),
                ('debt', models.FloatField()),
                ('pe_ratio', models.FloatField()),
                ('pb_ratio', models.FloatField()),
                ('divident', models.FloatField()),
                ('book_value', models.FloatField()),
                ('face_value', models.FloatField()),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockuser.stocks')),
            ],
        ),
    ]
