# Generated by Django 4.2.7 on 2024-06-21 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockuser', '0003_fundamental'),
    ]

    operations = [
        migrations.CreateModel(
            name='predictors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.FileField(upload_to='predictors/')),
                ('scalar', models.FileField(upload_to='predictors/')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockuser.stocks')),
            ],
        ),
    ]
