# Generated by Django 4.2.7 on 2024-06-25 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockuser', '0006_alter_stocks_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocks',
            name='description',
            field=models.TextField(default=1, max_length=1000),
        ),
    ]
